CREATE DATABASE IF NOT EXISTS Engaging_U; 
USE Engaging_U;

CREATE TABLE FEEDBACK
(QUESTION_ID INT NOT NULL,
QUESTION VARCHAR(100) NOT NULL,
CONSTRAINT QUESTION_ID_PK PRIMARY KEY (QUESTION_ID));

CREATE TABLE REMINDER
(
REMINDER_ID INT NOT NULL,
TIME_LEFT INT NOT NULL,
REMINDER_TEXT VARCHAR(100) NOT NULL,
CONSTRAINT REMINDER_PK PRIMARY KEY (REMINDER_ID)
);

CREATE TABLE TRAIL
(
TRAIL_ID INT NOT NULL,
TOTAL_TIME INT NOT NULL,
CONSTRAINT TRAIL_PK PRIMARY KEY (TRAIL_ID)
);

CREATE TABLE TRAIL_REMINDERS
(
TRAIL_ID INT NOT NULL,
REMINDER_ID INT NOT NULL,
CONSTRAINT TRAIL_REMINDERS_PK PRIMARY KEY (TRAIL_ID, REMINDER_ID)
);

CREATE TABLE TRAIL_INSTANCE
(
TRAIL_INSTANCE_ID VARCHAR(10) NOT NULL,
TRAIL_ID INT NOT NULL,
CONSTRAINT TRAIL_INSTANCE_PK PRIMARY KEY (TRAIL_INSTANCE_ID),
CONSTRAINT TRAIL_INSTANCE_FK1 FOREIGN KEY (TRAIL_ID)
REFERENCES TRAIL(TRAIL_ID) 
);

CREATE TABLE FEEDBACK_QUESTION
(
FEEDBACK_QUESTION_ID INT NOT NULL,
FEEDBACK_QUESTION VARCHAR(100) NOT NULL,
CONSTRAINT FEEDBACK_PK PRIMARY KEY (FEEDBACK_QUESTION_ID)
);

CREATE TABLE FEEDBACK_SUBMISSION
(
FEEDBACK_SUBMISSION_ID INT NOT NULL,
FEEDBACK_ANSWER VARCHAR(100) NOT NULL,
FEEDBACK_QUESTION_ID INT NOT NULL,
TRAIL_INSTANCE_ID VARCHAR(10) NOT NULL,
CONSTRAINT FEEDBACK_SUBMISSION_PK PRIMARY KEY (FEEDBACK_SUBMISSION_ID),
CONSTRAINT FEEDBACK_SUBMISSION_FK1 FOREIGN KEY (FEEDBACK_QUESTION_ID)
REFERENCES FEEDBACK_QUESTION(FEEDBACK_QUESTION_ID),
CONSTRAINT FEEDBACK_SUBMISSION_FK2 FOREIGN KEY (TRAIL_INSTANCE_ID)
REFERENCES TRAIL_INSTANCE(TRAIL_INSTANCE_ID)
);

CREATE TABLE TEAM
(
TEAM_ID INT NOT NULL,
TEAM_POINTS INT NOT NULL,
TRAIL_INSTANCE_ID VARCHAR(10) NOT NULL,
CONSTRAINT TEAM_PK PRIMARY KEY (TEAM_ID, TRAIL_INSTANCE_ID),
CONSTRAINT TEAM_FK1 FOREIGN KEY (TRAIL_INSTANCE_ID)
REFERENCES TRAIL_INSTANCE(TRAIL_INSTANCE_ID)
);

CREATE TABLE PARTICIPANT
(
USER_ID INT NOT NULL,
USERNAME VARCHAR(100) NOT NULL,
TEAM_ID INT NOT NULL,
CONSTRAINT PARTICIPANT_PK PRIMARY KEY (USER_ID),
CONSTRAINT PARTICIPANT_FK1 FOREIGN KEY (TEAM_ID)
REFERENCES TEAM(TEAM_ID)
);

CREATE TABLE AR_GAME
(
AR_GAME_ID INT NOT NULL,
AR_GAME_CODE VARCHAR(20) NOT NULL,
CONSTRAINT AR_GAME_PK PRIMARY KEY (AR_GAME_ID)
);

CREATE TABLE HOTSPOT
(
HOTSPOT_ID INT NOT NULL,
LATITUDE VARCHAR(20) NOT NULL,
LONGTITUDE VARCHAR(20) NOT NULL,
AR_GAME_ID INT NOT NULL,
CONSTRAINT HOTSPOT_PK PRIMARY KEY (HOTSPOT_ID),
CONSTRAINT HOTSPOT_FK1 FOREIGN KEY (AR_GAME_ID)
REFERENCES AR_GAME(AR_GAME_ID)
);

CREATE TABLE TRAIL_HOTSPOT
(
TRAIL_ID INT NOT NULL,
HOTSPOT_ID INT NOT NULL,
CONSTRAINT TRAIL_HOTSPOT_PK PRIMARY KEY (TRAIL_ID, HOTSPOT_ID),
CONSTRAINT TRAIL_HOTSPOT_FK1 FOREIGN KEY (TRAIL_ID)
REFERENCES TRAIL(TRAIL_ID),
CONSTRAINT TRAIL_HOTSPOT_FK2 FOREIGN KEY (HOTSPOT_ID)
REFERENCES HOTSPOT(HOTSPOT_ID)
);

CREATE TABLE MISSION
(
MISSION_ID INT NOT NULL,
HOTSPOT_ID INT NOT NULL,
CONSTRAINT MISSION_PK PRIMARY KEY (MISSION_ID),
CONSTRAINT MISSION_FK1 FOREIGN KEY (HOTSPOT_ID)
REFERENCES HOTSPOT(HOTSPOT_ID)
);

CREATE TABLE TRAIL_MISSION
(
TRAIL_ID INT NOT NULL,
MISSION_ID INT NOT NULL,
CONSTRAINT TRAIL_MISSION_PK PRIMARY KEY (TRAIL_ID,MISSION_ID),
CONSTRAINT TRAIL_MISSION_FK1 FOREIGN KEY (TRAIL_ID)
REFERENCES TRAIL(TRAIL_ID),
CONSTRAINT TRAIL_MISSION_FK2 FOREIGN KEY (MISSION_ID)
REFERENCES MISSION(MISSION_ID)
);

CREATE TABLE QUIZ
(
QUIZ_QUESTION VARCHAR(100) NOT NULL,
QUIZ_ANSWER VARCHAR(10) NOT NULL,
MISSION_ID INT NOT NULL,
CONSTRAINT QUIZ_PK PRIMARY KEY (QUIZ_QUESTION),
CONSTRAINT QUIZ_FK1 FOREIGN KEY (MISSION_ID)
REFERENCES MISSION(MISSION_ID)
);

CREATE TABLE QUIZ_OPTION
(
QUIZ_QUESTION VARCHAR(100) NOT NULL,
QUIZ_OPTION VARCHAR(10) NOT NULL,
CONSTRAINT QUIZ_OPTION_PK PRIMARY KEY (QUIZ_QUESTION, QUIZ_OPTION),
CONSTRAINT QUIZ_OPTION_FK1 FOREIGN KEY (QUIZ_QUESTION)
REFERENCES QUIZ(QUIZ_QUESTION)
);

CREATE TABLE SUBMISSION_QUESTION
(
QUESTION_ID INT NOT NULL,
QUESTION VARCHAR(100) NOT NULL,
MISSION_ID INT NOT NULL,
CONSTRAINT SUBMISSION_QUESTION_PK PRIMARY KEY (QUESTION_ID),
CONSTRAINT SUBMISSION_QUESTION_FK FOREIGN KEY (MISSION_ID)
REFERENCES MISSION(MISSION_ID)
);

CREATE TABLE SUBMISSION
(SUBMISSION_ID INT NOT NULL,
SUBMISSION_IMAGE_URL VARCHAR(100) NOT NULL,
TEAM_ID INT NOT NULL,
TRAIL_INSTANCE_ID VARCHAR(10) NOT NULL,
QUESTION_ID INT NOT NULL,
CONSTRAINT SUBMISSION_PK PRIMARY KEY (SUBMISSION_ID),
CONSTRAINT SUBMISSION_FK1 FOREIGN KEY (TEAM_ID)
REFERENCES TEAM(TEAM_ID),
CONSTRAINT SUBMISSION_FK2 FOREIGN KEY (QUESTION_ID)
REFERENCES SUBMISSION_QUESTION(QUESTION_ID),
CONSTRAINT SUBMISSION_FK3 FOREIGN KEY (TRAIL_INSTANCE_ID)
REFERENCES TRAIL_INSTANCE(TRAIL_INSTANCE_ID)
);